/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gmail.benlynn.waver;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int clown=0x7f020000;
        public static final int corpse=0x7f020001;
        public static final int dummy=0x7f020002;
        public static final int goblin=0x7f020003;
        public static final int missile=0x7f020004;
        public static final int shield=0x7f020005;
        public static final int stab=0x7f020006;
        public static final int wiz=0x7f020007;
        public static final int wound=0x7f020008;
    }
    public static final class id {
        public static final int arena=0x7f050002;
        public static final int arrow_view=0x7f050003;
        public static final int container=0x7f050000;
        public static final int mainview=0x7f050001;
        public static final int speech_box=0x7f050004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int SDtut=0x7f04001a;
        public static final int SDtut2=0x7f04001b;
        public static final int SDtut3=0x7f04001c;
        public static final int WFPtut=0x7f040014;
        public static final int WFPtut2=0x7f040015;
        public static final int WFPtut3=0x7f040016;
        public static final int WFPtutdraw=0x7f040019;
        public static final int WFPtutlose=0x7f040018;
        public static final int WFPtutwin=0x7f040017;
        public static final int app_name=0x7f040000;
        public static final int dummytut=0x7f040006;
        public static final int dummytut1=0x7f040007;
        public static final int dummytutdraw=0x7f040009;
        public static final int dummytutlose=0x7f04000a;
        public static final int dummytutwin=0x7f040008;
        public static final int howtoknife=0x7f040001;
        public static final int howtoknife2=0x7f040002;
        public static final int howtoknifepass1=0x7f040003;
        public static final int howtoknifepass2=0x7f040004;
        public static final int howtoknifepass3=0x7f040005;
        public static final int shieldtut=0x7f04000f;
        public static final int shieldtut2=0x7f040010;
        public static final int shieldtutdraw=0x7f040011;
        public static final int shieldtutlose=0x7f040013;
        public static final int shieldtutwin=0x7f040012;
        public static final int targettut=0x7f04000b;
        public static final int targettutdraw=0x7f04000d;
        public static final int targettutlose=0x7f04000e;
        public static final int targettutwin=0x7f04000c;
    }
}
